name: " Pull Power Platform changes"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to pull changes from
        required: true
      solutionFolder:
        description: Folder name of the Power Platform solution (leave empty to use AL-Go setting)
        required: false
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for PR/Commit?
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: pwsh

jobs:
  PullChanges:
    runs-on: [windows-latest]
    name: Pull changes from ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@PPP
        with:
          shell: pwsh
          eventId: "DO0103"

      - name: EnvName
        env:
          _environment: ${{ inputs.environment }}
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $envName = "$env:_environment".Split(' ')[0]
          Add-Content -encoding utf8 -Path $env:GITHUB_ENV -Value "envName=$envName"

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@PPP
        with:
          shell: pwsh
          get: powerPlatformSolutionFolder

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@PPP
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: '${{ env.envName }}-AuthContext,${{ env.envName }}_AuthContext,AuthContext,TokenForPush'
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Determine Deployment Environments
        id: DetermineDeploymentEnvironments
        uses: freddydk/AL-Go/Actions/DetermineDeploymentEnvironments@PPP
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: pwsh
          getEnvironments: ${{ inputs.environment }}
          type: 'Publish'

      - name: Set Power Platform solution folder
        env:
          _solutionFolder: ${{ inputs.solutionFolder }}
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $solutionFolder = $env:_solutionFolder
          if ($solutionFolder -eq '') {
            write-host "Solution folder is not provided. Taking the folder from AL-Go settings"
            $solutionFolder = $env:powerPlatformSolutionFolder
          }
          write-host "Solution folder: $solutionFolder"
          Add-Content -encoding utf8 -Path $env:GITHUB_ENV -Value "solutionFolder=$solutionFolder"

      - name: Pull changes from Power Platform environment
        uses: freddydk/AL-Go/Actions/PullPowerPlatformChanges@PPP
        env:
          Secrets: '${{ steps.ReadSecrets.outputs.Secrets }}'
        with:
          shell: pwsh
          actionsRepo: 'freddydk/AL-Go/Actions@PPP'
          token: ${{ steps.ReadSecrets.outputs.TokenForPush }}
          directCommit: ${{ inputs.directCommit }}
          environmentName: ${{ inputs.environment }}
          solutionFolder: ${{ env.solutionFolder }}
          deploymentEnvironmentsJson: ${{ steps.DetermineDeploymentEnvironments.outputs.deploymentEnvironmentsJson }}

      - name: Finalize the workflow
        if: always()
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@PPP
        with:
          shell: pwsh
          eventId: "DO0103"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
